console.log('Happy developing ✨')
console.log('Pedro SWE')
console.log('Adham SWE bardo')
console.log("Hello from eyad")
console.log("Hello from mn3m")
console.log("hello from Adham")
console.log("hello from Adham2")